language: python
python: 2.7
sudo: false
os:
  - linux
env:
  - TOX_ENV=lint
  - TOX_ENV=py27

install:
  - pip install tox

script:
  - sudo tox -e $TOX_ENV  # Got to run tests as root so they can access /etc/shadow file.
