language: python
python:
  - 2.7

# Used old infrastructure, needed for integration tests:
# http://docs.travis-ci.com/user/workers/standard-infrastructure/
sudo: required

os:
  - linux

env:
  - TASK=checks
  - TASK=integration

cache:
  directories:
    - $HOME/.cache/pip/

install:
  - pip install tox
  - pip install --upgrade pip
  - if [ ${TASK} = 'integration' ]; then sudo -E ./scripts/travis/prepare-integration.sh; fi

script:
  - ./scripts/travis/build.sh
